# Generated by Django 4.0.3 on 2022-04-10 10:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('releasedate', models.DateField()),
                ('logo', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('entry_fee', models.TextField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=4)),
                ('photo', models.CharField(blank=True, max_length=30)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('supported_games', models.ManyToManyField(to='tcgr.cardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=40)),
                ('age', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('avatar', models.CharField(blank=True, max_length=30)),
                ('gender', models.TextField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('cardgames', models.ManyToManyField(to='tcgr.cardgame')),
                ('likes', models.ManyToManyField(related_name='referee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
