# Generated by Django 4.0.3 on 2022-04-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('releasedate', models.DateField()),
                ('logo', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('entry_fee', models.TextField(blank=True, choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=4)),
                ('photo', models.CharField(blank=True, max_length=30)),
                ('supported_games', models.ManyToManyField(to='tcgr.cardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=40)),
                ('age', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('avatar', models.CharField(blank=True, max_length=30)),
                ('gender', models.TextField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('cardgames', models.ManyToManyField(to='tcgr.cardgame')),
            ],
        ),
    ]
