# Generated by Django 4.0.3 on 2022-04-07 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tcgr', '0002_categorystore_store_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
        migrations.AddField(
            model_name='referee',
            name='likes',
            field=models.ManyToManyField(related_name='referee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='entry_fee',
            field=models.TextField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=4),
        ),
    ]
