# Generated by Django 4.0.3 on 2022-04-08 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcgr', '0003_remove_store_category_referee_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
