# Generated by Django 4.0.3 on 2022-04-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcgr', '0004_store_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorystore',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
